### ISSUE TITLE
Unexpected token { in JSON at position 95

### ISSUE THREAD

**Issue by ckhatton-transreport** [browserslist/update-db#17]
I've simply run `npx browserslist@latest --update-db` and got the error:

```shell
SyntaxError: Unexpected token { in JSON at position 95
    at JSON.parse (<anonymous>)
    at getLatestInfo (/Users/foobar/.npm/_npx/072487b38308305a/node_modules/update-browserslist-db/index.js:62:19)
    at updateDB (/Users/foobar/.npm/_npx/072487b38308305a/node_modules/update-browserslist-db/index.js:264:16)
    at Object.<anonymous> (/Users/foobar/.npm/_npx/072487b38308305a/node_modules/browserslist/cli.js:42:3)
```

Maybe an additional curly brace has been added to the latest build by mistake?

**Comment by ai** [comment]
Check `yarn info caniuse-lite --json` output. The error happens because `yarn` outputs incorrect JSON.

**Comment by ckhatton-transreport** [comment]
Ar, I didn't realise browserslist is local, not global. Yeah the related project repo uses yarn.

I have put the output through an online JSON checker, and it reports nothing is wrong with it.

🤷

**Comment by ckhatton-transreport** [comment]
Oh weird, running `npx browserslist@latest --update-db` again has worked successfully, with warnings, but it worked.

```shell
✦ ❯ npx browserslist@latest --update-db
Latest version:     1.0.30001466
Installed version:  1.0.30001323
Removing old caniuse-lite from lock file
Installing new caniuse-lite version
```
