### ISSUE TITLE
consider making it a common basic library

### ISSUE THREAD

**Issue by nanianlisao** [browserslist/update-db#19]
Hey, we think the operation of updating the library version is a very general function. Have you considered separating it into a common basic library
I'm looking forward to seeing this happen！

**Comment by ai** [comment]
There are already many tools for that in npm.

Also, pnpm has built-in tool for that (I think that switching to `pnpm` is the best for all projects).

**Comment by nanianlisao** [comment]
But switching to PNPM cannot require cooperation from each project, especially when there are too many old projects

**Comment by nanianlisao** [comment]
> There are already many tools for that in npm.

@ai Can you help provide some similar tools? I am lacking in this area

**Comment by ai** [comment]
I have 20+ open source projects and switched to pnpm in most of them.

If you don’t want to switch there are many tools already top update nested dependencies for npm.

**Comment by ai** [comment]
> Can you help provide some similar tools? I am lacking in this area

I saw them a few years ago when developed this tool.

Right now I don’t want to spend time for investigation again.

In pnpm it is just `pnpm -r dependency`

**Comment by ai** [comment]
Anyway I don’t want to create a new tool and spend my time to support it, when there is a pnpm

**Comment by nanianlisao** [comment]
All right, Thanks for your patient answer
