### ISSUE TITLE
[feature request] Add support for the bun package manager

### ISSUE THREAD

**Issue by eelkevdbos** [browserslist/update-db#25]
Executing `bunx update-browserslist-db@latest` results in the following error:

```bash
update-browserslist-db: No lockfile found. Run "npm install", "yarn install" or "pnpm install"
```

Bun uses a binary lockfile called `bun.lockb` and at the time of writing has no built-in method yet to update individual packages.

**Comment by eelkevdbos** [comment]
I'm working on a draft PR and will post back as soon as I have a working setup.

**Comment by alec-c4** [comment]
Hey! Any update on this issue? @eelkevdbos

**Comment by hbibel** [comment]
Appears to be blocked by oven-sh/bun#6419

**Comment by SrBrahma** [comment]
Bun now supports it! https://github.com/oven-sh/bun/issues/6419#issuecomment-2179541513

**Comment by ai** [comment]
I need some Bun user to send PR. Here is what you need to do:

1. Add Bun detection here https://github.com/browserslist/update-db/blob/main/index.js#L41-L57
2. Add `caniuse-lite` latest version extraction here https://github.com/browserslist/update-db/blob/main/index.js#L63-L79
3. Add `caniuse-lite` update CLI call like this https://github.com/browserslist/update-db/blob/main/index.js#L288-L289
4. Add tests to `text/fixtures` and call them from `test/index.test.js`.

**Comment by ai** [comment]
Bun support added with 1.1. Thanks to @pornoiya and @kytta.

Note 2 limits:
1. You need to have `npm` to get latest `caniuse-lite` version.
2. It will add `caniuse-lite` to `dependencies`. https://github.com/browserslist/update-db/issues/42

We created issues in Bun repo to fix these limits.
