### ISSUE TITLE
npm version check

### ISSUE THREAD

**Issue by romanlex** [browserslist/update-db#30]
Why do you check npm version?
I don't see any engines directory in the package.json with restrictions on node version or npm version.

Example, node 14 + npm 6
If I remove check-npm-version.js all work perfectly

**Comment by ai** [comment]
I have it for ESLint to know what Node.js features to check (it will show an error if I use feature from Node.js 16).

**Comment by romanlex** [comment]
If you use features from node 14+ maybe you set engines directory in package.json?

**Comment by ai** [comment]
Oops, sorry I missed the open source project (too many). Here we do not have `engines` because it was used by Browserslist with Node.js ≥ 6 support.

Here is that issue with npm 6 why we decided to stop supporting it
https://github.com/browserslist/update-db/issues/1
