### ISSUE TITLE
Yarnpkg not found when attempting to collect latest info

### ISSUE THREAD

**Issue by mralaminahamed** [browserslist/update-db#33]
**Issue Description:**
When running the command to collect the latest information, the build process fails with an error indicating that the `yarnpkg` command is not found. This issue seems to be caused by a missing or outdated version of Yarn installed on the system.

**Steps to Reproduce:**
1. Clone the repository and navigate to the project directory.
2. Run the command or script responsible for collecting the latest information (e.g., `yarn collect-latest-info` or `npm run collect-latest-info`).
3. Observe the error message stating that the `yarnpkg` command is not found.

**Expected Behavior:**
The command or script should successfully run and collect the latest information without any errors related to missing dependencies or commands.

**Environment:**
- Operating System: [Specify your operating system and version]
- Node.js version: [Specify your Node.js version]
- Yarn version (if installed): [Specify your Yarn version, if applicable]

**Additional Information:**
- The issue occurs consistently across different machines and environments.
- Manually installing Yarn (if not already installed) or updating to the latest version does not resolve the problem.

**Possible Solutions:**
- Update the installation instructions or documentation to ensure that users have the required dependencies, including Yarn, installed correctly.
- Add a check in the build script or command to verify the presence of `yarnpkg` and provide a helpful error message or fallback option if it's not found.
- Consider implementing an automatic installation or update process for Yarn within the build script or command.

**Attachments:**
![Screenshot from 2024-04-29 20-45-24](https://github.com/browserslist/update-db/assets/34349365/2f32e78a-34d1-4c69-9d35-b57c4c4db1b7)

Please let me know if you need any further information or clarification regarding this issue.

**Comment by ai** [comment]
I reverted your changes, fixed pnpm 9 issue with test.

You need to prepare another PR this time not breaking the tests.

Use `pnpm unit` to run unit tests locally.

**Comment by mralaminahamed** [comment]
ok, i will.
