### ISSUE TITLE
lost package-lock.json indentation

### ISSUE THREAD

**Issue by alexanderanchishkin** [browserslist/update-db#4]
Line of code: [here](https://github.com/browserslist/update-db/blob/main/index.js#L107)
You can see that 2-space-indentation is hardcoded for new package-lock.json file.
Is it possible to detect package-lock.json indentation? And if no is it possible to make option "tabWidth" for set this value?

**Comment by ai** [comment]
It will be better to detect the origin indent from previous `package-lock.json`.

Can you send PR since i am locked on another open source project?

**Comment by alexanderanchishkin** [comment]
Yes I can. Thank you.

**Comment by ai** [comment]
Fixed in 1.0.6.
