### ISSUE TITLE
update to latest browserlist fails: "npx update-browserslist-db@latest"

### ISSUE THREAD

**Issue by un99known99** [browserslist/update-db#45]
trying to update via npx update-browserslist-db@latest", getting error:

Error: Command failed: npm install caniuse-lite
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: eslint-config-next@12.0.4
npm ERR! Found: eslint@8.15.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"*" from eslint-import-resolver-typescript@2.7.1
npm ERR!   node_modules/eslint-import-resolver-typescript
npm ERR!     eslint-import-resolver-typescript@"^2.4.0" from eslint-config-next@12.0.4
npm ERR!     node_modules/eslint-config-next
npm ERR!       dev eslint-config-next@"^12.0.4" from the root project
npm ERR!   peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8" from eslint-plugin-import@2.26.0
npm ERR!   node_modules/eslint-plugin-import
npm ERR!     eslint-plugin-import@"^2.22.1" from eslint-config-next@12.0.4
npm ERR!     node_modules/eslint-config-next
npm ERR!       dev eslint-config-next@"^12.0.4" from the root project
npm ERR!     peer eslint-plugin-import@"*" from eslint-import-resolver-typescript@2.7.1
npm ERR!     node_modules/eslint-import-resolver-typescript
npm ERR!       eslint-import-resolver-typescript@"^2.4.0" from eslint-config-next@12.0.4
npm ERR!       node_modules/eslint-config-next
npm ERR!         dev eslint-config-next@"^12.0.4" from the root project
npm ERR!   5 more (eslint-plugin-jsx-a11y, eslint-plugin-react, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^7.23.0" from eslint-config-next@12.0.4
npm ERR! node_modules/eslint-config-next
npm ERR!   dev eslint-config-next@"^12.0.4" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^7.23.0" from eslint-config-next@12.0.4
npm ERR!   node_modules/eslint-config-next
npm ERR!     dev eslint-config-next@"^12.0.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /root/.npm/_logs/2024-09-28T13_52_38_317Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-09-28T13_52_38_317Z-debug-0.log

    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at updatePackageManually (/root/.npm/_npx/2662cbd72e57abb6/node_modules/update-browserslist-db/index.js:233:5)
    at updateDB (/root/.npm/_npx/2662cbd72e57abb6/node_modules/update-browserslist-db/index.js:301:5)
    at Object.<anonymous> (/root/.npm/_npx/2662cbd72e57abb6/node_modules/update-browserslist-db/cli.js:34:5)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)

Problem with `npm install caniuse-lite` call. Run it manually.

![grafik](https://github.com/user-attachments/assets/8ffc9303-4668-415d-8a65-c178a0fc661d)

**Comment by ai** [comment]
You have a problem with your `package.json` dependencies. This is why `npm` fails. You need to solve them first.

**Comment by ai** [comment]
See the error stack. npm complains about eslint dependencies graph.

**Comment by un99known99** [comment]
@ai , thx for the quick answer, how to solve the package.json dependencies?

**Comment by ai** [comment]
You get paid for this job. It is unfair to ask free open source maintainer to do your job, when you will get paid for it, and open source developer get nothing.

**Comment by ai** [comment]
I recommend starting from reading npm error and checking manually all dependencies it mentioning.
